# Generated by Django 6.0.5 on 2026-08-02 06:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_type', models.CharField(choices=[('typer', 'Speed Typer'), ('bug', 'Bug Hunter'), ('complexity', 'Big-O Complexity Master'), ('parsons', 'Code Repair Shop'), ('predictor', 'Output Predictor')], max_length=20)),
                ('level', models.IntegerField(default=1)),
                ('score', models.IntegerField(default=0)),
                ('played_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_histories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Game Histories',
                'ordering': ['-played_at'],
            },
        ),
    ]
