# Generated by Django 6.0.5 on 2026-08-04 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_quiz_quizquestion_quizsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='difficulty',
            field=models.CharField(default='Basic to Advanced', help_text='Difficulty level e.g. Basic to Advanced', max_length=50),
        ),
        migrations.AddField(
            model_name='quiz',
            name='topic',
            field=models.CharField(default='General DSA', help_text='DSA Topic e.g. Array, String, Heap, DP', max_length=100),
        ),
    ]
