# Generated by Django 6.0.5 on 2026-08-07 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_quiz_difficulty_quiz_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamehistory',
            name='game_type',
            field=models.CharField(choices=[('typer', 'Speed Typer'), ('bug', 'Bug Hunter'), ('complexity', 'Big-O Complexity Master'), ('parsons', 'Code Repair Shop'), ('predictor', 'Output Predictor'), ('algo', 'Algorithm Sequence Master')], max_length=20),
        ),
    ]
