# Generated by Django 6.0.5 on 2026-08-12 12:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_gamehistory_game_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyResourcePlaylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('instructor', models.CharField(help_text='Instructor or YouTube Channel', max_length=150)),
                ('url', models.URLField(help_text='Playlist URL')),
                ('description', models.TextField(blank=True, default='')),
                ('badge_text', models.CharField(blank=True, default='Playlist', max_length=50)),
                ('section', models.CharField(choices=[('dsa', 'DSA Courses'), ('coding', 'Coding Platforms'), ('webdev', 'Web Development'), ('aiml', 'AI / ML'), ('aptitude', 'Aptitude & Quantitative'), ('softskills', 'Soft Skills & Communication')], default='dsa', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
