# Generated by Django 6.0.5 on 2026-08-12 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_customdsaproblem'),
    ]

    operations = [
        migrations.AddField(
            model_name='customdsaproblem',
            name='link_type',
            field=models.CharField(choices=[('problem', 'Coding Problem'), ('resource', 'Video / Resource Link')], default='problem', max_length=20),
        ),
        migrations.AlterField(
            model_name='customdsaproblem',
            name='url',
            field=models.URLField(help_text='Problem or resource URL e.g. LeetCode, YouTube, Docs'),
        ),
    ]
