# Generated by Django 6.0.5 on 2026-06-23 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_leetcode_easy_solved_user_leetcode_hard_solved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='completed_dsa_problems',
            field=models.JSONField(default=list),
        ),
    ]
