# Generated by Django 6.0.5 on 2026-06-27 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_completed_dsa_problems'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='game_bug_level',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='game_complexity_level',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='game_parsons_level',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='game_predictor_level',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='game_typer_level',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
