# Generated by Django 6.0.5 on 2026-08-07 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_game_bug_level_user_game_complexity_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='game_algo_level',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
