# Generated by Django 6.0.5 on 2026-08-10 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='badge',
            options={'ordering': ['questions_required', 'xp_required']},
        ),
        migrations.AddField(
            model_name='badge',
            name='questions_required',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='badge',
            name='tier',
            field=models.CharField(default='Bronze', max_length=20),
        ),
    ]
