# Generated by Django 6.0.5 on 2026-08-10 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume_analysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='resumeanalysis',
            table='resume_analysis_resumeanalysis',
        ),
    ]
