# Generated by Django 6.0.5 on 2026-05-10 09:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('DSA', 'Data Structures & Algorithms'), ('WEBDEV', 'Web Development'), ('COMM', 'Communication'), ('APT', 'Aptitude'), ('AIML', 'AI/ML'), ('CORE', 'Core Subjects'), ('OTHER', 'Other')], default='OTHER', max_length=10)),
                ('hours_practiced', models.DecimalField(decimal_places=1, default=0, max_digits=7)),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=15)),
                ('progress', models.PositiveIntegerField(default=0, help_text='Progress percentage 0-100')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-hours_practiced'],
                'unique_together': {('user', 'skill_name')},
            },
        ),
    ]
