# Generated by Django 6.0.5 on 2026-08-02 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='action_text',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='action_url',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='icon',
            field=models.CharField(default='bi-lightbulb-fill', max_length=50),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='impact_badge',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
